version: "3.9"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "31416:80"
    environment:
      TZ: 'Europe/Lisbon'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1;2606:4700:4700::1111;2606:4700:4700::1001
      WEBUIBOXEDLAYOUT: traditional
      VIRTUAL_HOST: pihole.internal.matiasilva.com
      QUERY_LOGGING: false
    volumes:
      - /home/pi/volumes/pihole/etc-pihole:/etc/pihole/
      - /home/pi/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/
    restart: unless-stopped
    networks:
      - saudade_docker

networks:
  saudade_docker:
    name: saudade_docker
    driver: bridge
